os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "4.6.0"
jdk:
  - oraclejdk8
install:
  - docker version
  - docker-compose version
  - npm install -g yarn
  - yarn global add yo
  - yo --version
script:
  - echo "hello"
