os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "4.4.4"
jdk:
  - oraclejdk8
install:
  - npm install -g npm
  - npm install -g yo bower gulp-cli
script:
  - java -version
  - git --version
  - mvn -v
  - node -v
  - npm -v
  - bower -v
  - yo --version
  - gulp -v
  - docker version
  - docker-compose version
  - ls -al $TRAVIS_BUILD_DIR
  - ls -al "$TRAVIS_BUILD_DIR"/generator-jhipster
  - sh install.sh
  # - sh test.sh
