sudo: required

services:
  - docker

before_install:
- docker build -t pascalgrimaud/jhipster-docker .
- docker run -d -p 8080:8080 -p 3000:3000 -p 3001:3001 -p 4022:22 -w /home/jhipster/jhipster-sample-app/ --name=jhipster pascalgrimaud/jhipster-docker mvn spring-boot:run ; sleep 120
- docker logs jhipster
- curl --retry 10 --retry-delay 5 -I http://localhost:8080/ | grep "HTTP/1.1 200 OK"
