sudo: required
group: edge
services:
  - docker
before_script:
  - docker pull tomcat
script:
  # - sudo service docker restart ; sleep 10
  - sudo iptables -L
  - docker version
  - docker info
  - docker run -d -p 8080:8080 tomcat
