os:
  - linux
services:
  - docker
language: java
jdk:
  - oraclejdk8
install:
  - docker run --name app-cassandra -d -p 7000:7000 -p 7001:7001 -p 7199:7199 -p 9042:9042 -p 9160:9160 cassandra:2.2
  - sleep 20
  - docker logs app-cassandra
  - cat cql/create-tables.cql >> cql/create-keyspace-prod.cql
  - cat cql/create-keyspace-prod.cql
  - docker cp cql/create-keyspace-prod.cql app-cassandra:create-keyspace-prod.cql
  - docker exec -it app-cassandra ls -l / /cql/
  - docker exec -it app-cassandra cqlsh -f /cql/create-keyspace-prod.cql
  - sleep 20
  - docker logs app-cassandra
script:
  - docker images
