sudo: required
services:
  - docker
before_script:
  - docker pull pascalgrimaud/tomcat
script:
  - docker version
  - docker info
  - docker ps -a
  - sudo iptables --list
  - docker run -d -p 8080:8080 pascalgrimaud/tomcat ; sleep 10
  - sudo iptables --list
  - docker run -d -p 8081:8080 pascalgrimaud/tomcat ; sleep 10
  - sudo iptables --list
  - docker run -d pascalgrimaud/tomcat ; sleep 10
  - sudo iptables --list
  # - docker logs jhipster
  # - curl --retry 10 --retry-delay 5 -I http://localhost:8080/ | grep "HTTP/1.1 200 OK"
