os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "4.4.1"
jdk:
  - oraclejdk8
before_install:
  - ls -l /usr/local/
  - ls -l /usr/local/phantomjs/
  - ls -l /usr/local/phantomjs-2.0.0/
install:
  - git clone https://github.com/jhipster/jhipster-travis-build.git
  - tar -xvf "$PWD"/jhipster-travis-build/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C "$PWD"/jhipster-travis-build/
  - mkdir /usr/local/phantomjs-2.1.1/
  - mv "$PWD"/jhipster-travis-build/phantomjs-2.1.1-linux-x86_64/LICENSE.BSD /usr/local/phantomjs-2.1.1/
  - mv "$PWD"/jhipster-travis-build/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/phantomjs-2.1.1/
  - ln -sf /usr/local/phantomjs-2.1.1/ /usr/local/phantomjs
  - ls -l /usr/local/
  - ls -l /usr/local/phantomjs/
  - ls -l /usr/local/phantomjs-2.1.1/
 script:
  - echo "hello script"
