os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "4.4.1"
jdk:
  - oraclejdk8
before_install:
  - ls -l /usr/local/
  - ls -l /usr/local/phantomjs/
  - ls -l /usr/local/phantomjs-2.0.0/
install:
  - echo "hello install"
script:
  - echo "hello script"
