os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "4.4.4"
jdk:
  - oraclejdk8
install:
  # - curl -L https://github.com/jhipster/jhipster-travis-build/archive/master.zip
  # - unzip jhipster-travis-build-master.zip
  # - ls -al jhipster-travis-build/
  - ./downloadFromGithub.sh
script:
  - echo "script"
