os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "4.4.4"
jdk:
  - oraclejdk8
install:
  - git clone https://github.com/jhipster/jhipster-travis-build.git
  - ls -al
  - wget https://github.com/jhipster/jhipster-travis-build/archive/master.zip
  - unzip master.zip > /dev/null
  - ls -al jhipster-travis-build-master/
script:
  - echo "script"
