os:
  - linux
services:
  - docker
sudo: required
language: node_js
node_js:
  - "4.2.1"
before_install:
  - sudo iptables -L
install:
  - npm install -g yo
#  - npm install -g generator-jhipster
  - cd $TRAVIS_BUILD_DIR/
  - git clone https://github.com/jhipster/generator-jhipster.git
  - cd $TRAVIS_BUILD_DIR/generator-jhipster
  - npm install
  - npm link
  - npm test
script:
  - echo hello
  - cd $TRAVIS_BUILD_DIR
  - mkdir test && cd test
  - yo jhipster
