os:
  - linux
services:
  - docker
sudo: required
before_install:
  - sudo iptables -L
  - service docker restart ; sleep 5
  - sudo iptables -L
install:
  - echo $TRAVIS_BUILD_DIR
  - pwd
  - docker ps -a
script:
  - echo hello
