os:
  - linux
services:
  - docker
sudo: required
language: node_js
node_js:
  - "4.2.1"
before_install:
  - sudo iptables -L
install:
  - docker version
script:
  - echo hello
  - echo "$TRAVIS_BUILD_DIR -> $DOCKER_LOGIN $DOCKER_PASSWORD"
