sudo: required
services:
  - docker
before_script:
  - docker pull pascalgrimaud/tomcat
script:
  - docker run -d -p 8080:8080 --name=jhipster pascalgrimaud/tomcat ; sleep 120
  - docker logs jhipster
  - curl --retry 10 --retry-delay 5 -I http://localhost:8080/ | grep "HTTP/1.1 200 OK"
